# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = ""
language = "javascript"
manifest_version = 3
name = "Enable modern web security headers to all responses"

[scripts]
build = "npm run build"
post_init = "npm install"

[local_server.backends.origin_0]
      url = "https://http-me.glitch.me/"

[setup.backends.origin_0]
address = "http-me.glitch.me"
port = 443
